### ISSUE TITLE
Query is getting printed.

### ISSUE THREAD

**Issue by mohitparyani** [miteshpithadiya/SearchableSpinner#11]
Hello,

I implemented this library in my project but when i type any query in searchview of the dialog box, Its getting printed above the search view in an transparent layout i tried to find out the issue but i got nothing. 
Can you tell me how to remove that transparent layout.

I have attached the screen shot bellow.
![device-2016-06-06-182713](https://cloud.githubusercontent.com/assets/19505680/15822606/64b73bc6-2c14-11e6-9bfe-4ed330e319aa.png)

**Comment by miteshpithadiya** [comment]
Hi,

I have resolved this issue in the latest version 1.3.0.

**Comment by mohitparyani** [comment]
Hello,

Thank you mitesh for the changes.
