### ISSUE TITLE
How to change the default string text

### ISSUE THREAD

**Issue by mrsolarius** [miteshpithadiya/SearchableSpinner#119]
Hi,
Firstly thanks this realy useful library...
But I need help ;) .
I want to use you module to develop a french app.
But I don't know how to translate your UI.
Can you explain how I can do this ? 

Thanks =)

**Comment by mrsolarius** [comment]
So I'm stupid x)

For people ask the same question...

The solution is to use the SearchableSpinner class not the Spinner class and use this methods : 
```java
searchableSpinnerObject.setTitle("Your title text");
searchableSpinnerObject.setPositiveButton("Your ok text");
```

**Comment by rahulkushwaha-techconfer** [comment]
does not work?
is searchableSpinnerObject a spinnerId?
