### ISSUE TITLE
java.lang.IllegalStateException: Fragment already added: SearchableListDialog{6a0eb11 #1 TAG}

### ISSUE THREAD

**Issue by AhmadRehan71** [miteshpithadiya/SearchableSpinner#123]
Fragment already added Exception occurs when double tap on the SearchableSpinner.

**Comment by erwinaji77n** [comment]
check this out, you can make custom library and edit library files like this https://github.com/miteshpithadiya/SearchableSpinner/pull/121/files

**Comment by AhmadRehan71** [comment]
@erwinaji77n I can't change the library files as they are read only files on my side. Only authorized person can change these files.

**Comment by erwinaji77n** [comment]
like i said before, you can create your own library based on this library, check this for reference to create new library files https://medium.com/@jasjot784/how-to-modify-an-android-library-in-7-steps-bf9c16aa6dfa

**Comment by erwinaji77n** [comment]
the author of this library seems not login for a long time, so the pull request from another user not accepted

**Comment by AhmadRehan71** [comment]
@erwinaji77n Thanks for such information. I will look into this.
Thanks.
