### ISSUE TITLE
Hey , can it init via java?

### ISSUE THREAD

**Issue by GuyDviri** [miteshpithadiya/SearchableSpinner#2]

**Comment by miteshpithadiya** [comment]
Yes, it can.

SearchableSpinner spinner = new SearchableSpinner(context);

**Comment by GuyDviri** [comment]
i mean init the list?

**Comment by miteshpithadiya** [comment]
Hi,

I am not sure about it. Can you please post your requirement in detail so that I can check if it can be implemented.

**Comment by pedrofsn** [comment]
Hi GuyDviri, here is how init list using Java:

```
List<String> lista = new ArrayList<>();
ArrayAdapter<String> adapter = new ArrayAdapter<>(this, android.R.layout.simple_list_item_1, lista);
searchableSpinner.setAdapter(adapter);
```
