### ISSUE TITLE
Fragment is java.lang.IllegalStateException: Fragment already added

### ISSUE THREAD

**Issue by filipjelic** [miteshpithadiya/SearchableSpinner#31]
Hi there,
could you add a method to check if the fragment is already added? This is a small issue, but it can be handled easy.
I'm getting this error, on fast double click...
  `java.lang.IllegalStateException: Fragment already added: SearchableListDialog{10fe7cc4 #0 TAG}`
```

**Comment by kbinfo4u** [comment]
Figure out the solution of this error
Just add a line into SearchableSpinner.java onTouch method and change the line 

**from:**
`_searchableListDialog.show(scanForActivity(_context).getFragmentManager(), "TAG");`

**to:**
`if (!_searchableListDialog.isAdded())
                    _searchableListDialog.show(scanForActivity(_context).getFragmentManager(), "TAG");`

**Comment by EffyCoder** [comment]
@kbinfo4u The solution you proposed needs to be implemented in the library itself or by the user of library?

**Comment by xeeshansami** [comment]
> Figure out the solution of this error
> Just add a line into SearchableSpinner.java onTouch method and change the line
> 
> **from:**
> `_searchableListDialog.show(scanForActivity(_context).getFragmentManager(), "TAG");`
> 
> **to:**
> `if (!_searchableListDialog.isAdded()) _searchableListDialog.show(scanForActivity(_context).getFragmentManager(), "TAG");`

resolved thanks
