### ISSUE TITLE
Textbox upon dialoginterface

### ISSUE THREAD

**Issue by aliguvenc** [miteshpithadiya/SearchableSpinner#5]
Hi,
First thanks for this library. Is there any way to hide black text bar upon the dialog interface which pops up while typing to seachview?

**Comment by lukaville** [comment]
http://stackoverflow.com/questions/20278385/how-to-remove-android-searchview-popup-text-while-searching

**Comment by miteshpithadiya** [comment]
Hi, sorry for the late response but as of now the library does not have a way to hide the black text bar, but will definitely provide a solution for this in future releases.

**Comment by aliguvenc** [comment]
Thanks for your response.
