### ISSUE TITLE
Refresh content

### ISSUE THREAD

**Issue by pedrofsn** [miteshpithadiya/SearchableSpinner#6]
The listview isn`t refreshed when you set a new adapter.

**Comment by ask4abid** [comment]
Hello , can you please have a look at the following issue and fix the gradle dependency as per the proposed solution ?

http://stackoverflow.com/questions/36012918/spinner-with-sub-spinner-not-working-as-expected/36793314?noredirect=1#comment61160834_36793314

Kind Regards,

Abid

**Comment by miteshpithadiya** [comment]
Hi, thanks for your questions. I will look at the solution and will update you as soon as possible.

**Comment by ask4abid** [comment]
Thanks , I will be waiting for an instant update!

**Comment by miteshpithadiya** [comment]
Hi, I have resolved the issue with a new solution. It should work fine now.

**Comment by ask4abid** [comment]
Hello,

Thank you very much.I will upddate you if I find any issue.

Really appriciated.

Kind regards
Abid.

**Comment by ahmedbilal360** [comment]
public void setisFromInit(Boolean isFromInit)
    {
        this._isFromInit=isFromInit;
        this._isDirty=isFromInit;
    }
