### ISSUE TITLE
[Feature Request] Spinner Hint

### ISSUE THREAD

**Issue by TurKurT656** [miteshpithadiya/SearchableSpinner#8]
Hi bro.
this is an awesome lib. can u add hint feature to spinner?
sometimes its better than the default selection

**Comment by ask4abid** [comment]
Hello Brother,

I hope you are doing great. This is a must have option to show Hint as a default readable text that will inform user about what to select from this Spinner.

Although we can set Title with this function " setTitle("Select Whaatever");" but this appears in the searchable list after the spinner is clicked .This will be really a huge favor to have this feature (HINT Feature) in searchable Spinner.

I hope to get the quick upgrade in this Great and useful Searchable Spinner.

Kind Regards,

Abid

**Comment by ask4abid** [comment]
@miteshpithadiya  Sir are you planning to implement this Hint feature to spinner ?

this has to be something that can be handled in java for the Development perspective as you already have added support for adding title e.g searchableSpinner.setTitle("whatever");

looking forward for this Enhancement .

Kind Regards,

Abid

**Comment by harry0880** [comment]
Hii,

Have you made this enhancement or not???

**Comment by miteshpithadiya** [comment]
Hi All,
Thank you for your suggestions, but I wish the keep the functionality of the library very similar to a normal android spinner. A normal spinner supports hint only for the spinner in a dialog view where the hint would be the title of the dialog view. Introducing this feature might just increase the complexity of this library which I do not intend to do.

Please let me know if I have understood the concern correctly or not.

**Comment by miteshpithadiya** [comment]
Hi All,

I have implemented the hint feature in version 1.3.0. Please have a look. If there is no action done on the spinner with the hint then getItemSelected() will return null and getSelectedItemPosition() would return NO_ITEM_SELECTED(-1)

**Comment by TurKurT656** [comment]
TnQ very much. :)

**Comment by harry0880** [comment]
Bro with this update the Search Dialog box in not opening Up on click of a Spinner.!!!:(
Please check!!!!

**Comment by miteshpithadiya** [comment]
Please share your code and give me some more details on the issue please.

**Comment by harry0880** [comment]
<com.toptoche.searchablespinnerlibrary.SearchableSpinner
        android:id="@+id/spDist"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        />

This I have added in in XML and filling data with ArrayList.

N running this code. 
 void setDistrictSpinner()
  {
    ArrayAdapter<District> Adapter = new ArrayAdapter<District>(getActivity(), android.R.layout.simple_spinner_item, db.getDistrict());
    Adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
    spDistrict.setAdapter(Adapter);
    spDistrict.setTitle("District");
  }


So problem is that when I touch the spinner, The search dialog box which used to open, is not opening now with the update provided

**Comment by harry0880** [comment]
Also Can you make one more enhancement i.e the dialog box opens on Touch Event.
I want it to get open on Click event !!!.  As I am using Scroll view and this creates problem.

**Comment by miteshpithadiya** [comment]
Hi, I have resolved the issue in new version 1.3.1. Please check.

**Comment by harry0880** [comment]
Thanxx bro... Now its working perfectly....

**Comment by arunarajput** [comment]
can anyone please help me? This is my query https://stackoverflow.com/questions/47278704/how-to-use-searchview-onquerytextlistener-in-searchable-spinner.
